data <- read.delim("household_power_consumption.txt", sep = ";", stringsAsFactors = F )
library(lubridate)
library(dplyr)
data <- mutate(data, Date = dmy(data$Date))
data1 <- subset(data, data$Date == "2007-02-01" | data$Date == "2007-02-02")
data1 <- mutate(data1, Global_active_power = as.numeric(data1$Global_active_power))
png(filename = "plot1.png", width = 480, height = 480, units = "px")
hist(data1$Global_active_power, col ="red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()
